apiVersion: v1
kind: Namespace
metadata:
  name: mcp-servers
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repos-pvc
  namespace: mcp-servers
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-git-server
  namespace: mcp-servers
  labels:
    app: mcp-git-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-git-server
  template:
    metadata:
      labels:
        app: mcp-git-server
    spec:
      containers:
      - name: mcp-git
        image: mcp-git:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: git-repos
          mountPath: /repos
      volumes:
      - name: git-repos
        persistentVolumeClaim:
          claimName: git-repos-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-git-service
  namespace: mcp-servers
spec:
  selector:
    app: mcp-git-server
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-git-ingress
  namespace: mcp-servers
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mcp-git.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mcp-git-service
            port:
              number: 8080 